-- PROPOSAL ONLY — DO NOT APPLY WITHOUT EXPLICIT APPROVAL.
-- Asset Tracker private-document metadata and audit design.
-- Storage bucket creation and storage.objects policies must be applied separately.

create table if not exists public.asset_documents (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid not null references public.assets(id) on delete restrict,
  document_type text not null check (document_type in (
    'title','bill_of_sale','registration','insurance','loan','tax','photo','other'
  )),
  storage_bucket text not null default 'asset-documents'
    check (storage_bucket = 'asset-documents'),
  storage_path text not null unique,
  original_name text not null,
  mime_type text not null,
  byte_size bigint not null check (byte_size > 0 and byte_size <= 26214400),
  sha256 text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  version_no integer not null default 1 check (version_no > 0),
  replaces_document_id uuid references public.asset_documents(id) on delete restrict,
  status text not null default 'active'
    check (status in ('active','replaced','archived','quarantined')),
  uploaded_by uuid default auth.uid(),
  uploaded_email text default lower(auth.jwt() ->> 'email'),
  created_at timestamptz not null default now(),
  status_changed_at timestamptz not null default now(),
  unique (asset_id, document_type, sha256)
);

create index if not exists idx_asset_documents_asset
  on public.asset_documents(asset_id, document_type, created_at desc);
create index if not exists idx_asset_documents_status
  on public.asset_documents(status, created_at desc);

create table if not exists public.asset_document_history (
  id bigint generated by default as identity primary key,
  document_id uuid not null,
  asset_id uuid not null,
  op text not null check (op in ('UPLOAD','REPLACE','ARCHIVE','PURGE')),
  actor_id uuid,
  actor_email text,
  changed_at timestamptz not null default now(),
  storage_path text,
  sha256 text,
  changes jsonb not null default '{}'::jsonb
);

create index if not exists idx_asset_document_history_document
  on public.asset_document_history(document_id, changed_at desc);
create index if not exists idx_asset_document_history_asset
  on public.asset_document_history(asset_id, changed_at desc);

alter table public.asset_documents enable row level security;
alter table public.asset_document_history enable row level security;

create policy "auth read asset documents" on public.asset_documents
  for select to authenticated using (true);

-- Replace the hard-coded editor list with an approved role table or custom JWT
-- claim before applying. A dedicated Hermes identity is intentionally absent
-- until Jon approves its exact address and scope.
create policy "editors insert asset documents" on public.asset_documents
  for insert to authenticated
  with check (lower(auth.jwt() ->> 'email') = any
    (array['jonj@360-llc.com','margi@360-llc.com']));

create policy "editors update asset documents" on public.asset_documents
  for update to authenticated
  using (lower(auth.jwt() ->> 'email') = any
    (array['jonj@360-llc.com','margi@360-llc.com']))
  with check (lower(auth.jwt() ->> 'email') = any
    (array['jonj@360-llc.com','margi@360-llc.com']));

create policy "auth read asset document history" on public.asset_document_history
  for select to authenticated using (true);

-- No DELETE policies are proposed. Routine removal is a status change.
-- Audit-trigger/RPC definitions and storage.objects policies belong in the
-- reviewed migration after identity, retention, and download-scope decisions.
